server:
#  port: 12345
  port: 8088
  servlet:
    context-path: /
  jetty:
    acceptors: 1
    selectors: 2

spring:
  application:
    name: mybatis-curd

  datasource:
    username: root
    password: cybtsl0704
    url: jdbc:mysql://localhost:3306/poetry_appreciation?zeroDateTimeBehavior=convertToNull&useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC&autoReconnect=true

#    username: robot
#    password: PH$eI%S0q@gja6hF
#    url: jdbc:mysql://106.14.136.38:3306/poetry_appreciation?zeroDateTimeBehavior=convertToNull&useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC&autoReconnect=true

#    password: a1234
#    url: jdbc:mysql://192.168.1.110:3306/robot?zeroDateTimeBehavior=convertToNull&useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC&autoReconnect=true
    continue-on-error: true
    sql-script-encoding: UTF-8
    driver-class-name: com.mysql.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      initial-size: 2
      min-idle: 2
      max-active: 4
      max-wait: 60000
      # 间隔多久进行一次检测，检测需要关闭的空闲连接
      time-between-eviction-runs-millis: 60000
      # 一个连接在池中最小生存的时间
      min-evictable-idle-time-millis: 300000
      validation-query: SELECT 1 FROM DUAL
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      pool-prepared-statements: true
      max-pool-prepared-statement-per-connection-size: 20
      connect-properties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
      use-global-data-source-stat: true
      filters: stat,wall,log4j2
  #静态资源访问前缀
  mvc:
    static-path-pattern: /images/**

  #静态资源路径
  resources:
    static-locations: file:/Users/cyb/work/KaiFa/webdata/poetry/

  #文件上传大小限制
  servlet:
    multipart:
      enabled: true
      max-file-size: 100MB
      max-request-size: 150MB



mybatis-plus:
  call-setters-on-nulls: true;
  type-aliases-package: com.poetryappreciation.pojo
  mapper-locations: classpath:mapping/*.xml
  configuration:
    map-underscore-to-camel-case: true
    # 打印sql, 方便调试
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    use-generated-keys: true
    default-statement-timeout: 60
    default-fetch-size: 100
    call-setters-on-nulls: true

upload:
  url: /Users/cyb/work/KaiFa/webdata/poetry/
